# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  schedule: [{cron: "0 7 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.classic.svg
          
          # Options
          user: y2-znt
          template: classic
          base: header, activity, community, repositories
          base_indepth: yes
          config_timezone: Europe/Paris
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_stars: yes
          plugin_stars_limit: 4
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_notable: yes
